<?php

namespace CMS\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
	use Softdeletes;
    protected $fillable = ['parent_id','status'];

    public function detail()
    {
    	return $this->hasOne(CategoryDetail::class)->where('lang_id',default_lang());
    }

    public function details()
    {
        return $this->hasMany(CategoryDetail::class);
    }

    public function childrens()
    {
    	return $this->hasMany(Category::class,'parent_id')->orderBy('order');
    }

    public function pages()
    {
        return $this->belongsToMany(Page::class);
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::deleting(function ($category){
            $category->details()->each(function ($detail)
            {
                $detail->delete();
            });
            $category->childrens()->each(function ($children)
            {
                $children->details()->each(function($detail){
                    $detail->delete();
                });
                $children->delete();
            });
        });
    }
}
